[package]
name = "cedar-client"
version = "0.1.0"
edition = "2021"

[dependencies]
nx-pkg4 = { path = "../nx-pkg4" }
tokio = { version = "1.42.0", features = ["full"] }
winit = "0.30.5"
wgpu = "23.0.1"
